### ISSUE TITLE
Possible issue with mmol data

### ISSUE THREAD

**Issue by peterlynton** [chasepeeler/GlucoseViewer#8]
Nightscout URL is correct and Open Nightcout button works correctly.

Error message in Xcode debug window:

`typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "bgs", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "bgdelta", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil))`

**Comment by chasepeeler** [comment]
Would it be possible for you to show me what your API output looks like? It's <nightscouturl>/pebble

**Comment by peterlynton** [comment]
Sure:
`{"status":[{"now":1674219321863}],"bgs":[{"sgv":"6.9","trend":5,"direction":"FortyFiveDown","datetime":1674219262021,"bgdelta":"-0.8","battery":"85","iob":"1.25","bwp":"-1.49","bwpo":-2,"cob":23.2}],"cals":[]}`

**Comment by chasepeeler** [comment]
I see the issue. The bgdelta value is a string instead of int (even if it wasn't a string, it still would have failed since it would be a double and not an int). I actually split the API logic out last night and wrote unit tests for it, so this should be pretty simple for me take care this weekend.

**Comment by chasepeeler** [comment]
@peterlynton You mentioned using xcode. If you want to grab the refactorapi branch and give that a try, it should work better. I had to add in support for mmol/L units in addition to fixing the API parsing to deal with values possibly coming in different types. 

I went ahead and added support for either having a fixed set of values on the y-axis:
- 50-300 by 25 for mg/dL
- 2.8 - 16.6 by 0.6 for mmol/L 
or a dynamic set of values:
- min-10 to max+20 by 10 for mg/dL
- min-1.0 to max+1.5 by 0.5 for mmol/L 
where min and max are the minimum and maximum glucose readings among the 20 that are graphed

I don't really know what good values are to use for the fixed or dynamic ranges on mmol/L, so if you have any suggestions, please let me know. That's potentially something I could add to the settings, but I don't want that screen to get too bloated.

**Comment by peterlynton** [comment]
@chasepeeler Thanks for the update - trialled today using the refactorapi branch and displaying mmol/L values successfully.

Personally I wouldn't generally need a range of 2.8 to 16.6 mmol/L but appreciate that it may be required by some - my BG data is generally between 3.5 and 9 mmol/L.  Dynamic range suits my data perfectly.
